/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supermarket.view;

/**
 *
 * @author Chamidu
 */
public class CustomerView extends javax.swing.JFrame {

    /**
     * Creates new form CustomerView
     */
    public CustomerView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Basepanel = new javax.swing.JPanel();
        Headpanel = new javax.swing.JPanel();
        Customer = new javax.swing.JLabel();
        Formpanel = new javax.swing.JPanel();
        custidlabel = new javax.swing.JLabel();
        cusidtest = new javax.swing.JTextField();
        custitlelabel = new javax.swing.JLabel();
        custiteltest = new javax.swing.JTextField();
        custfirstnamelabel = new javax.swing.JLabel();
        cusfirstnametest = new javax.swing.JTextField();
        cuslastnamelabel = new javax.swing.JLabel();
        cuslastnametest = new javax.swing.JTextField();
        cusaddresslabel = new javax.swing.JLabel();
        cusaddresstest = new javax.swing.JTextField();
        cuszipcodelabel = new javax.swing.JLabel();
        cuszipcodetest = new javax.swing.JTextField();
        cusagelabel = new javax.swing.JLabel();
        cusagetest = new javax.swing.JTextField();
        cusmobilenumberlabel = new javax.swing.JLabel();
        cusmobilenumbertest = new javax.swing.JTextField();
        addbutton = new javax.swing.JButton();
        deletebutton = new javax.swing.JButton();
        updatebutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Customer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Customer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Customer.setText("Customer");
        Customer.setToolTipText("");

        javax.swing.GroupLayout HeadpanelLayout = new javax.swing.GroupLayout(Headpanel);
        Headpanel.setLayout(HeadpanelLayout);
        HeadpanelLayout.setHorizontalGroup(
            HeadpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Customer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        HeadpanelLayout.setVerticalGroup(
            HeadpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Customer, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        custidlabel.setText("Id");

        custitlelabel.setText("Titel");

        custfirstnamelabel.setText("First Name");

        cuslastnamelabel.setText("Last Name");

        cusaddresslabel.setText("Address");

        cuszipcodelabel.setText("Zip Code");

        cusagelabel.setText("Age");

        cusmobilenumberlabel.setText("Mobile Number");

        addbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addbutton.setText("Save");

        deletebutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deletebutton.setText("Delete");

        updatebutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updatebutton.setText("Update");

        javax.swing.GroupLayout FormpanelLayout = new javax.swing.GroupLayout(Formpanel);
        Formpanel.setLayout(FormpanelLayout);
        FormpanelLayout.setHorizontalGroup(
            FormpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FormpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(custitlelabel)
                    .addComponent(custfirstnamelabel)
                    .addComponent(custidlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cusaddresslabel)
                    .addComponent(cuszipcodelabel)
                    .addComponent(cusagelabel)
                    .addComponent(cusmobilenumberlabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cusagetest, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(custiteltest, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cusidtest, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cusaddresstest, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuszipcodetest, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cusmobilenumbertest, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FormpanelLayout.createSequentialGroup()
                        .addComponent(cusfirstnametest, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(FormpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(FormpanelLayout.createSequentialGroup()
                                .addComponent(updatebutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deletebutton)
                                .addGap(67, 67, 67)
                                .addComponent(addbutton)
                                .addGap(22, 22, 22))
                            .addGroup(FormpanelLayout.createSequentialGroup()
                                .addComponent(cuslastnamelabel)
                                .addGap(65, 65, 65)
                                .addComponent(cuslastnametest, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        FormpanelLayout.setVerticalGroup(
            FormpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FormpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(custidlabel)
                    .addComponent(cusidtest, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(custitlelabel)
                    .addComponent(custiteltest, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(custfirstnamelabel)
                    .addComponent(cusfirstnametest, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuslastnamelabel)
                    .addComponent(cuslastnametest, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cusaddresslabel)
                    .addComponent(cusaddresstest, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuszipcodelabel)
                    .addComponent(cuszipcodetest, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cusagelabel)
                    .addComponent(cusagetest, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cusmobilenumberlabel)
                    .addComponent(cusmobilenumbertest, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FormpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addbutton)
                    .addComponent(deletebutton)
                    .addComponent(updatebutton))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BasepanelLayout = new javax.swing.GroupLayout(Basepanel);
        Basepanel.setLayout(BasepanelLayout);
        BasepanelLayout.setHorizontalGroup(
            BasepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Headpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Formpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BasepanelLayout.setVerticalGroup(
            BasepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BasepanelLayout.createSequentialGroup()
                .addComponent(Headpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Formpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Basepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Basepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Basepanel;
    private javax.swing.JLabel Customer;
    private javax.swing.JPanel Formpanel;
    private javax.swing.JPanel Headpanel;
    private javax.swing.JButton addbutton;
    private javax.swing.JLabel cusaddresslabel;
    private javax.swing.JTextField cusaddresstest;
    private javax.swing.JLabel cusagelabel;
    private javax.swing.JTextField cusagetest;
    private javax.swing.JTextField cusfirstnametest;
    private javax.swing.JTextField cusidtest;
    private javax.swing.JLabel cuslastnamelabel;
    private javax.swing.JTextField cuslastnametest;
    private javax.swing.JLabel cusmobilenumberlabel;
    private javax.swing.JTextField cusmobilenumbertest;
    private javax.swing.JLabel custfirstnamelabel;
    private javax.swing.JLabel custidlabel;
    private javax.swing.JTextField custiteltest;
    private javax.swing.JLabel custitlelabel;
    private javax.swing.JLabel cuszipcodelabel;
    private javax.swing.JTextField cuszipcodetest;
    private javax.swing.JButton deletebutton;
    private javax.swing.JButton updatebutton;
    // End of variables declaration//GEN-END:variables
}
